version: "3.7"
services:
  backend:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      HTTP_SERVER_PORT: "8888"
      GRPC_SERVER_PORT: "9999"
    ports:
      - 9999:9999
      - 8888:8888
