# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: health.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='health.proto',
  package='',
  syntax='proto3',
  serialized_options=b'Z\006/proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0chealth.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x19\n\x07\x42linked\x12\x0e\n\x06\x61mount\x18\x01 \x01(\r2;\n\x06Health\x12\x31\n\x0bUserBlinked\x12\x08.Blinked\x1a\x16.google.protobuf.Empty(\x01\x42\x08Z\x06/protob\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_BLINKED = _descriptor.Descriptor(
  name='Blinked',
  full_name='Blinked',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='amount', full_name='Blinked.amount', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=70,
)

DESCRIPTOR.message_types_by_name['Blinked'] = _BLINKED
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Blinked = _reflection.GeneratedProtocolMessageType('Blinked', (_message.Message,), {
  'DESCRIPTOR' : _BLINKED,
  '__module__' : 'health_pb2'
  # @@protoc_insertion_point(class_scope:Blinked)
  })
_sym_db.RegisterMessage(Blinked)


DESCRIPTOR._options = None

_HEALTH = _descriptor.ServiceDescriptor(
  name='Health',
  full_name='Health',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=72,
  serialized_end=131,
  methods=[
  _descriptor.MethodDescriptor(
    name='UserBlinked',
    full_name='Health.UserBlinked',
    index=0,
    containing_service=None,
    input_type=_BLINKED,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_HEALTH)

DESCRIPTOR.services_by_name['Health'] = _HEALTH

# @@protoc_insertion_point(module_scope)
